### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pdias** [widop/WidopGoogleAnalyticsBundle#17]
Hello in my config i do this:

```
widop_google_analytics:
    client_id:        "XXXXXXXXXX-5esdvefbcmov0fo6ohp2feeqp8cfrj27@developer.gserviceaccount.com"
    #profile_id:       "ga:XXXXXXX"
    profile_id:       "XXXXXXXXXX-5esdvefbcmov0fo6ohp2feeqp8cfrj27.apps.googleusercontent.com"
    private_key_file: "%kernel.root_dir%/Resources/key/8a2345bae89bb1c793ffe921e370c1ec9a6e2cfe-privatekey.p12"
    http_adapter:     "widop_http_adapter.curl"
```

But it always gives this error:

```
An error occured when fetching the URL via cURL. 

......vendor\widop\http-adapter-bundle\Widop\HttpAdapterBundle\Model\CurlHttpAdapter.php at line 66

```

Probably my settings/config are incorrect ...

Thanks,

Paulo

**Comment by egeloen** [comment]
Your configuration should look like:

``` yaml
widop_google_analytics:
    profile_id: 'ga:XXXXXXXX'
    client_id: XXXXXXXXXXXX@developer.gserviceaccount.com
    private_key_file: %kernel.root_dir%/app/Resources/bin/certificate.p12
```
